version: '3.4'

# Common variables
x-common-variables: &common-variables
  HBFDHOSTPORT: ${HBFDHOSTPORT}

x-xxx-common-services-config: &common-services-config
  restart: always

x-mongo-secrets: &mongo-credentials
  MONGO_USER: &mongo-user ${MONGO_USER}
  MONGO_PASS: &mongo-pass ${MONGO_PASS}
  MONGO_RSN: ${MONGO_RSN}
  MONGO_AUTH_DB: ${MONGO_AUTH_DB}
  MONGO_PORT: ${MONGO_PORT}
  MONGO_DB_NAME: ${MONGO_DB_NAME}

x-kafka-env: &kafka-env
  KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
  KAFKA_ADVERTISED_PORT: ${KAFKA_ADVERTISED_PORT}
  BROKER_ID_COMMAND: ${BROKER_ID_COMMAND}
  KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
  KAFKA_CREATE_TOPICS: ${KAFKA_CREATE_TOPICS}
  KAFKA_LISTENERS: ${KAFKA_LISTENERS}

x-kafka-conf: &kafka-conf
  KAFKA_ORDERS_TOPIC: ${KAFKA_ORDERS_TOPIC}
  KAFKA_LOGGING_TOPIC: ${KAFKA_LOGGING_TOPIC}
  KAFKA_ORDER_PAID_KEY: ${KAFKA_ORDER_PAID_KEY}
  KAFKA_BAD_IPN_ERROR_KEY: ${KAFKA_BAD_IPN_ERROR_KEY}
  KAFKA_BAD_BUSINESS_EMAIL_KEY: ${KAFKA_BAD_BUSINESS_EMAIL_KEY}
  KAFKA_HTTP_ERROR_KEY: ${KAFKA_HTTP_ERROR_KEY}

x-heart-beat-conf: &hb-conf
  HEART_BEAT_PORT: ${HEART_BEAT_PORT}
  HEART_BEAT_ENDPOINT: ${HEART_BEAT_ENDPOINT}
  HEART_BEAT_PERIOD: ${HEART_BEAT_PERIOD}

x-paypal-conf: &paypal-conf
  MY_PAYPAL_ACCOUNT: ${MY_PAYPAL_ACCOUNT}
  PAYPAL_ENDPOINT: ${PAYPAL_ENDPOINT}
  
x-gestionepagamenti-conf: &gestionepagamenti-conf
  DATASOURCE_HOST: ${MYSQL_HOST}
  DATASOURCE_USER: ${MYSQL_USER}
  DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
  DATASOURCE_NAME: ${MYSQL_DATABASE}
  DATASOURCE_PORT: ${MYSQL_PORT}
  PAYPAL_ACCOUNT: ${MY_PAYPAL_ACCOUNT}
  KAFKA_HOST: ${KAFKA_HOST}
  KAFKA_PORT: ${KAFKA_ADVERTISED_PORT}
  KAFKA_TOPIC1: ${KAFKA_ORDERS_TOPIC}
  KAFKA_TOPIC2: ${KAFKA_LOGGING_TOPIC}
  APP_NAME: ${APP_NAME}
  APP_PORT: ${APP_PORT}
  
x-common-php-variables: &common-php-variables
  PMA_HOST: ${MYSQL_HOST}
  PMA_PORT: ${MYSQL_PORT}
  PMA_USER: ${MYSQL_USER}
  PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  MYSQL_USER: ${MYSQL_USER}

services:

  payment-microservice:
    image: oraziosantonocito/dsbd.2020-santonocito_palumbo:payment-microservice
    <<: *common-services-config
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      MONGO_HOST: mongo
      SERVICE_NAME: payment-microservice
      HEART_BEAT_HOST: payment-microservice
      <<: *mongo-credentials
      <<: *kafka-conf
      <<: *hb-conf
      <<: *paypal-conf
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - kafka
      - zookeeper

  mongo:
    image: oraziosantonocito/dsbd.2020-santonocito_palumbo:payment-microservice-db
    <<: *common-services-config
    environment:
      MONGO_INITDB_ROOT_USERNAME: *mongo-user
      MONGO_INITDB_ROOT_PASSWORD: *mongo-pass
    volumes:
      - mongodb-data-volume:/data/db

  pingackfd1:
    <<: *common-services-config
    build:
      context: .
      dockerfile: PingAckFD1/PingAckFaultDetector/Dockerfile
    ports:
      - "8080:8080"
    environment:
      <<: *common-variables
      HOST_LIST: ${HOST_LIST}
      PING_POOLING_TIME: ${PING_POOLING_TIME}
      HEARTBEAT_RESEND_TIME: ${HEARTBEAT_RESEND_TIME}

  zoo:
    <<: *common-services-config
    image: library/zookeeper:3.4.13
    environment:
      <<: *common-variables
      ZOO_MY_ID: 1

  kafka:
    <<: *common-services-config
    environment:
      <<: *common-variables
      <<: *kafka-env
    image: wurstmeister/kafka:2.11-2.0.0
  
  mysqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mystorage:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8082:80'
    environment:
      <<: *common-php-variables
      
  gestionepagamenti:
    image: antonioimp/impala_diblasi_gestionepagamenti
    build:
      context: .
      dockerfile: gestionepagamenti/Dockerfile
    ports:
      - "2222:2222"
    depends_on:
      - kafka
      - mysqldb
    restart: always
    environment:
      <<: *gestionepagamenti-conf

volumes:
  mystorage:
  mongodb-data-volume:
