apiVersion: v1
kind: ConfigMap
metadata:
  name: modulo1-env
data:
  KAFKA_ADDRESS: kafka:9092
  KAFKA_GROUP_ID: modulo1-group
  KAFKA_MAIN_TOPIC: main-topic
  MONGODB_HOSTNAME: modulo1-db
  MONGODB_PORT: "27017"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: modulo1-db-env
  namespace: default
data:
  MONGO_INITDB_DATABASE: admin
