apiVersion: v1
data:
  MONGO_INITDB_ROOT_PASSWORD: MTIwOA==
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_PASS: MTIwOA==
  MONGO_USER: cm9vdA==
kind: Secret
metadata:
  name: payment-microservice-db-secret
  namespace: default
type: Opaque
