apiVersion: v1
kind: ConfigMap
metadata:
  name: pingack-env
data:
  PING_TIME: "30" # in seconds
  HOSTS_LIST: orders-service,shipping-service,products-service,payments-service
  BOOTSTRAP_ADDRESS: kafkabroker.default.svc.cluster.local:9092
