apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service-db
spec:
  selector:
    matchLabels:
      app: shipping-service-db
  template:
    metadata:
      labels:
        app: shipping-service-db
    spec:
      containers:
        - name: shipping-service-db
          image: mongo:latest
          ports:
            - containerPort: 27017
          envFrom:
            - configMapRef:
                name: shipping-service-db-env-file
            - secretRef:
                name: shipping-service-db-secret-file
          volumeMounts:
            - mountPath: /data/db
              name: shipping-service-db-volume
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 10
            timeoutSeconds: 1
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
        - name: shipping-service-db-volume
          persistentVolumeClaim:
            claimName: shipping-db-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
spec:
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      initContainers:
        - name: waitmongo
          image: mongo
          command:
            - sh
            - -c
            - |
              env | grep MONGO
              while ! mongo --host $MONGODB_HOSTNAME --port $MONGODB_PORT -u $MONGO_INITDB_ROOT_USERNAME \
              -p $MONGO_INITDB_ROOT_PASSWORD --eval 'db.adminCommand("ping")' > /dev/null 2>&1; do
                echo waiting for db
                sleep 2
              done
          envFrom:
            - configMapRef:
                name: shipping-service-env-file
            - configMapRef:
                name: shipping-service-db-env-file
            - secretRef:
                name: shipping-service-db-secret-file
      containers:
        - name: shipping-service
          image: andreaarciprete/arciprete-chiavetta-progetto-9b:shipping-manager-v5
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: shipping-service-db-env-file
            - configMapRef:
                name: shipping-service-env-file
            - secretRef:
                name: shipping-service-db-secret-file
          livenessProbe:
            httpGet:
              path: /ping1
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ping1
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 3
